// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class CourseContent
    {
        public int CourseId { get; set; }
        public int CourseId100 { get; set; }
        public int Coursechapter { get; set; }
        public string ChapterName { get; set; }
        public string Video { get; set; }
    }
}