// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vue.Models
{
    public partial class CourseDetail
    {
        public int CourseId { get; set; }
        public int SkillId { get; set; }
    }
}